export const DELETE_INGREDIENT: string = 'DELETE_INGREDIENT';
export const ADD_BUN_INGREDIENT: string = 'ADD_BUN_INGREDIENT';
export const ADD_UNLOCKED_INGREDIENT: string = 'ADD_UNLOCKED_INGREDIENT';
export const DELETE_ALL_INGREDIENTS:  string = 'DELETE_ALL_INGREDIENTS';
export const UPDATE_UNLOCKED: string = 'UPDATE_UNLOCKED';