export const DELETE_INGREDIENT = 'DELETE_INGREDIENT';
export const ADD_BUN_INGREDIENT = 'ADD_BUN_INGREDIENT';
export const ADD_UNLOCKED_INGREDIENT = 'ADD_UNLOCKED_INGREDIENT';
export const DELETE_ALL_INGREDIENTS = 'DELETE_ALL_INGREDIENTS';
export const UPDATE_UNLOCKED = 'UPDATE_UNLOCKED';